//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : ReaderClass.sm
//

#ifndef READERCLASS_SM_H
#define READERCLASS_SM_H


#define SMC_USES_IOSTREAMS

#include "statemap.h"

// Forward declarations.
class RMap;
class RMap_Start;
class RMap_Type;
class RMap_NumP;
class RMap_Num;
class RMap_Body;
class RMap_Sms;
class RMap_NoSms;
class RMap_OK;
class RMap_Error;
class RMap_Default;
class ReaderClassState;
class ReaderClassContext;
class ReaderClass;

class ReaderClassState :
    public statemap::State
{
public:

    ReaderClassState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(ReaderClassContext&) {};
    virtual void Exit(ReaderClassContext&) {};

    virtual void Colon(ReaderClassContext& context);
    virtual void Comma(ReaderClassContext& context);
    virtual void Dig(ReaderClassContext& context, char c);
    virtual void EOS(ReaderClassContext& context);
    virtual void EqualSign(ReaderClassContext& context);
    virtual void Lit(ReaderClassContext& context, char c);
    virtual void Plus(ReaderClassContext& context);
    virtual void Reset(ReaderClassContext& context);
    virtual void Semicolon(ReaderClassContext& context);
    virtual void Unknown(ReaderClassContext& context);

protected:

    virtual void Default(ReaderClassContext& context);
};

class RMap
{
public:

    static RMap_Start Start;
    static RMap_Type Type;
    static RMap_NumP NumP;
    static RMap_Num Num;
    static RMap_Body Body;
    static RMap_Sms Sms;
    static RMap_NoSms NoSms;
    static RMap_OK OK;
    static RMap_Error Error;
};

class RMap_Default :
    public ReaderClassState
{
public:

    RMap_Default(const char * const name, const int stateId)
    : ReaderClassState(name, stateId)
    {};

    virtual void Dig(ReaderClassContext& context, char c);
    virtual void Lit(ReaderClassContext& context, char c);
    virtual void Plus(ReaderClassContext& context);
    virtual void Colon(ReaderClassContext& context);
    virtual void Comma(ReaderClassContext& context);
    virtual void Semicolon(ReaderClassContext& context);
    virtual void EqualSign(ReaderClassContext& context);
    virtual void Unknown(ReaderClassContext& context);
    virtual void EOS(ReaderClassContext& context);
    virtual void Reset(ReaderClassContext& context);
};

class RMap_Start :
    public RMap_Default
{
public:
    RMap_Start(const char * const name, const int stateId)
    : RMap_Default(name, stateId)
    {};

    virtual void Lit(ReaderClassContext& context, char c);
};

class RMap_Type :
    public RMap_Default
{
public:
    RMap_Type(const char * const name, const int stateId)
    : RMap_Default(name, stateId)
    {};

    virtual void Colon(ReaderClassContext& context);
    virtual void Lit(ReaderClassContext& context, char c);
};

class RMap_NumP :
    public RMap_Default
{
public:
    RMap_NumP(const char * const name, const int stateId)
    : RMap_Default(name, stateId)
    {};

    virtual void Plus(ReaderClassContext& context);
};

class RMap_Num :
    public RMap_Default
{
public:
    RMap_Num(const char * const name, const int stateId)
    : RMap_Default(name, stateId)
    {};

    virtual void Comma(ReaderClassContext& context);
    virtual void Dig(ReaderClassContext& context, char c);
    virtual void Semicolon(ReaderClassContext& context);
};

class RMap_Body :
    public RMap_Default
{
public:
    RMap_Body(const char * const name, const int stateId)
    : RMap_Default(name, stateId)
    {};

    virtual void EqualSign(ReaderClassContext& context);
    virtual void Lit(ReaderClassContext& context, char c);
};

class RMap_Sms :
    public RMap_Default
{
public:
    RMap_Sms(const char * const name, const int stateId)
    : RMap_Default(name, stateId)
    {};

    virtual void Comma(ReaderClassContext& context);
    virtual void Dig(ReaderClassContext& context, char c);
    virtual void EOS(ReaderClassContext& context);
    virtual void Lit(ReaderClassContext& context, char c);
};

class RMap_NoSms :
    public RMap_Default
{
public:
    RMap_NoSms(const char * const name, const int stateId)
    : RMap_Default(name, stateId)
    {};

    virtual void EOS(ReaderClassContext& context);
};

class RMap_OK :
    public RMap_Default
{
public:
    RMap_OK(const char * const name, const int stateId)
    : RMap_Default(name, stateId)
    {};

};

class RMap_Error :
    public RMap_Default
{
public:
    RMap_Error(const char * const name, const int stateId)
    : RMap_Default(name, stateId)
    {};

};

class ReaderClassContext :
    public statemap::FSMContext
{
public:

    explicit ReaderClassContext(ReaderClass& owner)
    : FSMContext(RMap::Start),
      _owner(owner)
    {};

    ReaderClassContext(ReaderClass& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline ReaderClass& getOwner()
    {
        return (_owner);
    };

    inline ReaderClassState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<ReaderClassState&>(*_state);
    };

    inline void Colon()
    {
        getState().Colon(*this);
    };

    inline void Comma()
    {
        getState().Comma(*this);
    };

    inline void Dig(char c)
    {
        getState().Dig(*this, c);
    };

    inline void EOS()
    {
        getState().EOS(*this);
    };

    inline void EqualSign()
    {
        getState().EqualSign(*this);
    };

    inline void Lit(char c)
    {
        getState().Lit(*this, c);
    };

    inline void Plus()
    {
        getState().Plus(*this);
    };

    inline void Reset()
    {
        getState().Reset(*this);
    };

    inline void Semicolon()
    {
        getState().Semicolon(*this);
    };

    inline void Unknown()
    {
        getState().Unknown(*this);
    };

private:
    ReaderClass& _owner;
};


#endif // READERCLASS_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
